/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimuladoTokenRouteImport } from './routes/simulado.$token'
import { Route as SimuladoTokenIndexRouteImport } from './routes/simulado.$token.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSimuladosIndexRouteImport } from './routes/_authenticated/admin/simulados/index'
import { Route as AuthenticatedAdminRespostasIndexRouteImport } from './routes/_authenticated/admin/respostas/index'
import { Route as AuthenticatedAdminQuestoesIndexRouteImport } from './routes/_authenticated/admin/questoes/index'
import { Route as AuthenticatedAdminGruposIndexRouteImport } from './routes/_authenticated/admin/grupos/index'
import { Route as AuthenticatedAdminFeedbacksIndexRouteImport } from './routes/_authenticated/admin/feedbacks/index'
import { Route as AuthenticatedAdminEstudantesIndexRouteImport } from './routes/_authenticated/admin/estudantes/index'
import { Route as AuthenticatedAdminBancoQuestoesIndexRouteImport } from './routes/_authenticated/admin/banco-questoes/index'
import { Route as SimuladoTokenSessaoSessaoIdRouteImport } from './routes/simulado.$token.sessao.$sessaoId'
import { Route as AuthenticatedAdminSimuladosNovoRouteImport } from './routes/_authenticated/admin/simulados/novo'
import { Route as AuthenticatedAdminSimuladosIdRouteImport } from './routes/_authenticated/admin/simulados/$id'
import { Route as AuthenticatedAdminQuestoesNovoRouteImport } from './routes/_authenticated/admin/questoes/novo'
import { Route as AuthenticatedAdminQuestoesIdRouteImport } from './routes/_authenticated/admin/questoes/$id'
import { Route as AuthenticatedAdminGruposIdRouteImport } from './routes/_authenticated/admin/grupos/$id'
import { Route as AuthenticatedAdminEstudantesIdRouteImport } from './routes/_authenticated/admin/estudantes/$id'
import { Route as AuthenticatedAdminSimuladosIdSimulacaoRouteImport } from './routes/_authenticated/admin/simulados/$id.simulacao'
import { Route as AuthenticatedAdminSimuladosIdPreviaRouteImport } from './routes/_authenticated/admin/simulados/$id.previa'
import { Route as AuthenticatedAdminRespostasSessaoSessaoIdRouteImport } from './routes/_authenticated/admin/respostas/sessao.$sessaoId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoTokenRoute = SimuladoTokenRouteImport.update({
  id: '/simulado/$token',
  path: '/simulado/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladoTokenIndexRoute = SimuladoTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimuladoTokenRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSimuladosIndexRoute =
  AuthenticatedAdminSimuladosIndexRouteImport.update({
    id: '/admin/simulados/',
    path: '/admin/simulados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRespostasIndexRoute =
  AuthenticatedAdminRespostasIndexRouteImport.update({
    id: '/admin/respostas/',
    path: '/admin/respostas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestoesIndexRoute =
  AuthenticatedAdminQuestoesIndexRouteImport.update({
    id: '/admin/questoes/',
    path: '/admin/questoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGruposIndexRoute =
  AuthenticatedAdminGruposIndexRouteImport.update({
    id: '/admin/grupos/',
    path: '/admin/grupos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFeedbacksIndexRoute =
  AuthenticatedAdminFeedbacksIndexRouteImport.update({
    id: '/admin/feedbacks/',
    path: '/admin/feedbacks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEstudantesIndexRoute =
  AuthenticatedAdminEstudantesIndexRouteImport.update({
    id: '/admin/estudantes/',
    path: '/admin/estudantes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBancoQuestoesIndexRoute =
  AuthenticatedAdminBancoQuestoesIndexRouteImport.update({
    id: '/admin/banco-questoes/',
    path: '/admin/banco-questoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SimuladoTokenSessaoSessaoIdRoute =
  SimuladoTokenSessaoSessaoIdRouteImport.update({
    id: '/sessao/$sessaoId',
    path: '/sessao/$sessaoId',
    getParentRoute: () => SimuladoTokenRoute,
  } as any)
const AuthenticatedAdminSimuladosNovoRoute =
  AuthenticatedAdminSimuladosNovoRouteImport.update({
    id: '/admin/simulados/novo',
    path: '/admin/simulados/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSimuladosIdRoute =
  AuthenticatedAdminSimuladosIdRouteImport.update({
    id: '/admin/simulados/$id',
    path: '/admin/simulados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestoesNovoRoute =
  AuthenticatedAdminQuestoesNovoRouteImport.update({
    id: '/admin/questoes/novo',
    path: '/admin/questoes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestoesIdRoute =
  AuthenticatedAdminQuestoesIdRouteImport.update({
    id: '/admin/questoes/$id',
    path: '/admin/questoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGruposIdRoute =
  AuthenticatedAdminGruposIdRouteImport.update({
    id: '/admin/grupos/$id',
    path: '/admin/grupos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEstudantesIdRoute =
  AuthenticatedAdminEstudantesIdRouteImport.update({
    id: '/admin/estudantes/$id',
    path: '/admin/estudantes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSimuladosIdSimulacaoRoute =
  AuthenticatedAdminSimuladosIdSimulacaoRouteImport.update({
    id: '/simulacao',
    path: '/simulacao',
    getParentRoute: () => AuthenticatedAdminSimuladosIdRoute,
  } as any)
const AuthenticatedAdminSimuladosIdPreviaRoute =
  AuthenticatedAdminSimuladosIdPreviaRouteImport.update({
    id: '/previa',
    path: '/previa',
    getParentRoute: () => AuthenticatedAdminSimuladosIdRoute,
  } as any)
const AuthenticatedAdminRespostasSessaoSessaoIdRoute =
  AuthenticatedAdminRespostasSessaoSessaoIdRouteImport.update({
    id: '/admin/respostas/sessao/$sessaoId',
    path: '/admin/respostas/sessao/$sessaoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/simulado/$token': typeof SimuladoTokenRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/simulado/$token/': typeof SimuladoTokenIndexRoute
  '/admin/estudantes/$id': typeof AuthenticatedAdminEstudantesIdRoute
  '/admin/grupos/$id': typeof AuthenticatedAdminGruposIdRoute
  '/admin/questoes/$id': typeof AuthenticatedAdminQuestoesIdRoute
  '/admin/questoes/novo': typeof AuthenticatedAdminQuestoesNovoRoute
  '/admin/simulados/$id': typeof AuthenticatedAdminSimuladosIdRouteWithChildren
  '/admin/simulados/novo': typeof AuthenticatedAdminSimuladosNovoRoute
  '/simulado/$token/sessao/$sessaoId': typeof SimuladoTokenSessaoSessaoIdRoute
  '/admin/banco-questoes/': typeof AuthenticatedAdminBancoQuestoesIndexRoute
  '/admin/estudantes/': typeof AuthenticatedAdminEstudantesIndexRoute
  '/admin/feedbacks/': typeof AuthenticatedAdminFeedbacksIndexRoute
  '/admin/grupos/': typeof AuthenticatedAdminGruposIndexRoute
  '/admin/questoes/': typeof AuthenticatedAdminQuestoesIndexRoute
  '/admin/respostas/': typeof AuthenticatedAdminRespostasIndexRoute
  '/admin/simulados/': typeof AuthenticatedAdminSimuladosIndexRoute
  '/admin/respostas/sessao/$sessaoId': typeof AuthenticatedAdminRespostasSessaoSessaoIdRoute
  '/admin/simulados/$id/previa': typeof AuthenticatedAdminSimuladosIdPreviaRoute
  '/admin/simulados/$id/simulacao': typeof AuthenticatedAdminSimuladosIdSimulacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/simulado/$token': typeof SimuladoTokenIndexRoute
  '/admin/estudantes/$id': typeof AuthenticatedAdminEstudantesIdRoute
  '/admin/grupos/$id': typeof AuthenticatedAdminGruposIdRoute
  '/admin/questoes/$id': typeof AuthenticatedAdminQuestoesIdRoute
  '/admin/questoes/novo': typeof AuthenticatedAdminQuestoesNovoRoute
  '/admin/simulados/$id': typeof AuthenticatedAdminSimuladosIdRouteWithChildren
  '/admin/simulados/novo': typeof AuthenticatedAdminSimuladosNovoRoute
  '/simulado/$token/sessao/$sessaoId': typeof SimuladoTokenSessaoSessaoIdRoute
  '/admin/banco-questoes': typeof AuthenticatedAdminBancoQuestoesIndexRoute
  '/admin/estudantes': typeof AuthenticatedAdminEstudantesIndexRoute
  '/admin/feedbacks': typeof AuthenticatedAdminFeedbacksIndexRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposIndexRoute
  '/admin/questoes': typeof AuthenticatedAdminQuestoesIndexRoute
  '/admin/respostas': typeof AuthenticatedAdminRespostasIndexRoute
  '/admin/simulados': typeof AuthenticatedAdminSimuladosIndexRoute
  '/admin/respostas/sessao/$sessaoId': typeof AuthenticatedAdminRespostasSessaoSessaoIdRoute
  '/admin/simulados/$id/previa': typeof AuthenticatedAdminSimuladosIdPreviaRoute
  '/admin/simulados/$id/simulacao': typeof AuthenticatedAdminSimuladosIdSimulacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/simulado/$token': typeof SimuladoTokenRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/simulado/$token/': typeof SimuladoTokenIndexRoute
  '/_authenticated/admin/estudantes/$id': typeof AuthenticatedAdminEstudantesIdRoute
  '/_authenticated/admin/grupos/$id': typeof AuthenticatedAdminGruposIdRoute
  '/_authenticated/admin/questoes/$id': typeof AuthenticatedAdminQuestoesIdRoute
  '/_authenticated/admin/questoes/novo': typeof AuthenticatedAdminQuestoesNovoRoute
  '/_authenticated/admin/simulados/$id': typeof AuthenticatedAdminSimuladosIdRouteWithChildren
  '/_authenticated/admin/simulados/novo': typeof AuthenticatedAdminSimuladosNovoRoute
  '/simulado/$token/sessao/$sessaoId': typeof SimuladoTokenSessaoSessaoIdRoute
  '/_authenticated/admin/banco-questoes/': typeof AuthenticatedAdminBancoQuestoesIndexRoute
  '/_authenticated/admin/estudantes/': typeof AuthenticatedAdminEstudantesIndexRoute
  '/_authenticated/admin/feedbacks/': typeof AuthenticatedAdminFeedbacksIndexRoute
  '/_authenticated/admin/grupos/': typeof AuthenticatedAdminGruposIndexRoute
  '/_authenticated/admin/questoes/': typeof AuthenticatedAdminQuestoesIndexRoute
  '/_authenticated/admin/respostas/': typeof AuthenticatedAdminRespostasIndexRoute
  '/_authenticated/admin/simulados/': typeof AuthenticatedAdminSimuladosIndexRoute
  '/_authenticated/admin/respostas/sessao/$sessaoId': typeof AuthenticatedAdminRespostasSessaoSessaoIdRoute
  '/_authenticated/admin/simulados/$id/previa': typeof AuthenticatedAdminSimuladosIdPreviaRoute
  '/_authenticated/admin/simulados/$id/simulacao': typeof AuthenticatedAdminSimuladosIdSimulacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/simulado/$token'
    | '/admin/'
    | '/simulado/$token/'
    | '/admin/estudantes/$id'
    | '/admin/grupos/$id'
    | '/admin/questoes/$id'
    | '/admin/questoes/novo'
    | '/admin/simulados/$id'
    | '/admin/simulados/novo'
    | '/simulado/$token/sessao/$sessaoId'
    | '/admin/banco-questoes/'
    | '/admin/estudantes/'
    | '/admin/feedbacks/'
    | '/admin/grupos/'
    | '/admin/questoes/'
    | '/admin/respostas/'
    | '/admin/simulados/'
    | '/admin/respostas/sessao/$sessaoId'
    | '/admin/simulados/$id/previa'
    | '/admin/simulados/$id/simulacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/simulado/$token'
    | '/admin/estudantes/$id'
    | '/admin/grupos/$id'
    | '/admin/questoes/$id'
    | '/admin/questoes/novo'
    | '/admin/simulados/$id'
    | '/admin/simulados/novo'
    | '/simulado/$token/sessao/$sessaoId'
    | '/admin/banco-questoes'
    | '/admin/estudantes'
    | '/admin/feedbacks'
    | '/admin/grupos'
    | '/admin/questoes'
    | '/admin/respostas'
    | '/admin/simulados'
    | '/admin/respostas/sessao/$sessaoId'
    | '/admin/simulados/$id/previa'
    | '/admin/simulados/$id/simulacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/simulado/$token'
    | '/_authenticated/admin/'
    | '/simulado/$token/'
    | '/_authenticated/admin/estudantes/$id'
    | '/_authenticated/admin/grupos/$id'
    | '/_authenticated/admin/questoes/$id'
    | '/_authenticated/admin/questoes/novo'
    | '/_authenticated/admin/simulados/$id'
    | '/_authenticated/admin/simulados/novo'
    | '/simulado/$token/sessao/$sessaoId'
    | '/_authenticated/admin/banco-questoes/'
    | '/_authenticated/admin/estudantes/'
    | '/_authenticated/admin/feedbacks/'
    | '/_authenticated/admin/grupos/'
    | '/_authenticated/admin/questoes/'
    | '/_authenticated/admin/respostas/'
    | '/_authenticated/admin/simulados/'
    | '/_authenticated/admin/respostas/sessao/$sessaoId'
    | '/_authenticated/admin/simulados/$id/previa'
    | '/_authenticated/admin/simulados/$id/simulacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SimuladoTokenRoute: typeof SimuladoTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado/$token': {
      id: '/simulado/$token'
      path: '/simulado/$token'
      fullPath: '/simulado/$token'
      preLoaderRoute: typeof SimuladoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulado/$token/': {
      id: '/simulado/$token/'
      path: '/'
      fullPath: '/simulado/$token/'
      preLoaderRoute: typeof SimuladoTokenIndexRouteImport
      parentRoute: typeof SimuladoTokenRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/simulados/': {
      id: '/_authenticated/admin/simulados/'
      path: '/admin/simulados'
      fullPath: '/admin/simulados/'
      preLoaderRoute: typeof AuthenticatedAdminSimuladosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/respostas/': {
      id: '/_authenticated/admin/respostas/'
      path: '/admin/respostas'
      fullPath: '/admin/respostas/'
      preLoaderRoute: typeof AuthenticatedAdminRespostasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questoes/': {
      id: '/_authenticated/admin/questoes/'
      path: '/admin/questoes'
      fullPath: '/admin/questoes/'
      preLoaderRoute: typeof AuthenticatedAdminQuestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/grupos/': {
      id: '/_authenticated/admin/grupos/'
      path: '/admin/grupos'
      fullPath: '/admin/grupos/'
      preLoaderRoute: typeof AuthenticatedAdminGruposIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/feedbacks/': {
      id: '/_authenticated/admin/feedbacks/'
      path: '/admin/feedbacks'
      fullPath: '/admin/feedbacks/'
      preLoaderRoute: typeof AuthenticatedAdminFeedbacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/estudantes/': {
      id: '/_authenticated/admin/estudantes/'
      path: '/admin/estudantes'
      fullPath: '/admin/estudantes/'
      preLoaderRoute: typeof AuthenticatedAdminEstudantesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banco-questoes/': {
      id: '/_authenticated/admin/banco-questoes/'
      path: '/admin/banco-questoes'
      fullPath: '/admin/banco-questoes/'
      preLoaderRoute: typeof AuthenticatedAdminBancoQuestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/simulado/$token/sessao/$sessaoId': {
      id: '/simulado/$token/sessao/$sessaoId'
      path: '/sessao/$sessaoId'
      fullPath: '/simulado/$token/sessao/$sessaoId'
      preLoaderRoute: typeof SimuladoTokenSessaoSessaoIdRouteImport
      parentRoute: typeof SimuladoTokenRoute
    }
    '/_authenticated/admin/simulados/novo': {
      id: '/_authenticated/admin/simulados/novo'
      path: '/admin/simulados/novo'
      fullPath: '/admin/simulados/novo'
      preLoaderRoute: typeof AuthenticatedAdminSimuladosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/simulados/$id': {
      id: '/_authenticated/admin/simulados/$id'
      path: '/admin/simulados/$id'
      fullPath: '/admin/simulados/$id'
      preLoaderRoute: typeof AuthenticatedAdminSimuladosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questoes/novo': {
      id: '/_authenticated/admin/questoes/novo'
      path: '/admin/questoes/novo'
      fullPath: '/admin/questoes/novo'
      preLoaderRoute: typeof AuthenticatedAdminQuestoesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questoes/$id': {
      id: '/_authenticated/admin/questoes/$id'
      path: '/admin/questoes/$id'
      fullPath: '/admin/questoes/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuestoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/grupos/$id': {
      id: '/_authenticated/admin/grupos/$id'
      path: '/admin/grupos/$id'
      fullPath: '/admin/grupos/$id'
      preLoaderRoute: typeof AuthenticatedAdminGruposIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/estudantes/$id': {
      id: '/_authenticated/admin/estudantes/$id'
      path: '/admin/estudantes/$id'
      fullPath: '/admin/estudantes/$id'
      preLoaderRoute: typeof AuthenticatedAdminEstudantesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/simulados/$id/simulacao': {
      id: '/_authenticated/admin/simulados/$id/simulacao'
      path: '/simulacao'
      fullPath: '/admin/simulados/$id/simulacao'
      preLoaderRoute: typeof AuthenticatedAdminSimuladosIdSimulacaoRouteImport
      parentRoute: typeof AuthenticatedAdminSimuladosIdRoute
    }
    '/_authenticated/admin/simulados/$id/previa': {
      id: '/_authenticated/admin/simulados/$id/previa'
      path: '/previa'
      fullPath: '/admin/simulados/$id/previa'
      preLoaderRoute: typeof AuthenticatedAdminSimuladosIdPreviaRouteImport
      parentRoute: typeof AuthenticatedAdminSimuladosIdRoute
    }
    '/_authenticated/admin/respostas/sessao/$sessaoId': {
      id: '/_authenticated/admin/respostas/sessao/$sessaoId'
      path: '/admin/respostas/sessao/$sessaoId'
      fullPath: '/admin/respostas/sessao/$sessaoId'
      preLoaderRoute: typeof AuthenticatedAdminRespostasSessaoSessaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminSimuladosIdRouteChildren {
  AuthenticatedAdminSimuladosIdPreviaRoute: typeof AuthenticatedAdminSimuladosIdPreviaRoute
  AuthenticatedAdminSimuladosIdSimulacaoRoute: typeof AuthenticatedAdminSimuladosIdSimulacaoRoute
}

const AuthenticatedAdminSimuladosIdRouteChildren: AuthenticatedAdminSimuladosIdRouteChildren =
  {
    AuthenticatedAdminSimuladosIdPreviaRoute:
      AuthenticatedAdminSimuladosIdPreviaRoute,
    AuthenticatedAdminSimuladosIdSimulacaoRoute:
      AuthenticatedAdminSimuladosIdSimulacaoRoute,
  }

const AuthenticatedAdminSimuladosIdRouteWithChildren =
  AuthenticatedAdminSimuladosIdRoute._addFileChildren(
    AuthenticatedAdminSimuladosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEstudantesIdRoute: typeof AuthenticatedAdminEstudantesIdRoute
  AuthenticatedAdminGruposIdRoute: typeof AuthenticatedAdminGruposIdRoute
  AuthenticatedAdminQuestoesIdRoute: typeof AuthenticatedAdminQuestoesIdRoute
  AuthenticatedAdminQuestoesNovoRoute: typeof AuthenticatedAdminQuestoesNovoRoute
  AuthenticatedAdminSimuladosIdRoute: typeof AuthenticatedAdminSimuladosIdRouteWithChildren
  AuthenticatedAdminSimuladosNovoRoute: typeof AuthenticatedAdminSimuladosNovoRoute
  AuthenticatedAdminBancoQuestoesIndexRoute: typeof AuthenticatedAdminBancoQuestoesIndexRoute
  AuthenticatedAdminEstudantesIndexRoute: typeof AuthenticatedAdminEstudantesIndexRoute
  AuthenticatedAdminFeedbacksIndexRoute: typeof AuthenticatedAdminFeedbacksIndexRoute
  AuthenticatedAdminGruposIndexRoute: typeof AuthenticatedAdminGruposIndexRoute
  AuthenticatedAdminQuestoesIndexRoute: typeof AuthenticatedAdminQuestoesIndexRoute
  AuthenticatedAdminRespostasIndexRoute: typeof AuthenticatedAdminRespostasIndexRoute
  AuthenticatedAdminSimuladosIndexRoute: typeof AuthenticatedAdminSimuladosIndexRoute
  AuthenticatedAdminRespostasSessaoSessaoIdRoute: typeof AuthenticatedAdminRespostasSessaoSessaoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEstudantesIdRoute: AuthenticatedAdminEstudantesIdRoute,
  AuthenticatedAdminGruposIdRoute: AuthenticatedAdminGruposIdRoute,
  AuthenticatedAdminQuestoesIdRoute: AuthenticatedAdminQuestoesIdRoute,
  AuthenticatedAdminQuestoesNovoRoute: AuthenticatedAdminQuestoesNovoRoute,
  AuthenticatedAdminSimuladosIdRoute:
    AuthenticatedAdminSimuladosIdRouteWithChildren,
  AuthenticatedAdminSimuladosNovoRoute: AuthenticatedAdminSimuladosNovoRoute,
  AuthenticatedAdminBancoQuestoesIndexRoute:
    AuthenticatedAdminBancoQuestoesIndexRoute,
  AuthenticatedAdminEstudantesIndexRoute:
    AuthenticatedAdminEstudantesIndexRoute,
  AuthenticatedAdminFeedbacksIndexRoute: AuthenticatedAdminFeedbacksIndexRoute,
  AuthenticatedAdminGruposIndexRoute: AuthenticatedAdminGruposIndexRoute,
  AuthenticatedAdminQuestoesIndexRoute: AuthenticatedAdminQuestoesIndexRoute,
  AuthenticatedAdminRespostasIndexRoute: AuthenticatedAdminRespostasIndexRoute,
  AuthenticatedAdminSimuladosIndexRoute: AuthenticatedAdminSimuladosIndexRoute,
  AuthenticatedAdminRespostasSessaoSessaoIdRoute:
    AuthenticatedAdminRespostasSessaoSessaoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SimuladoTokenRouteChildren {
  SimuladoTokenIndexRoute: typeof SimuladoTokenIndexRoute
  SimuladoTokenSessaoSessaoIdRoute: typeof SimuladoTokenSessaoSessaoIdRoute
}

const SimuladoTokenRouteChildren: SimuladoTokenRouteChildren = {
  SimuladoTokenIndexRoute: SimuladoTokenIndexRoute,
  SimuladoTokenSessaoSessaoIdRoute: SimuladoTokenSessaoSessaoIdRoute,
}

const SimuladoTokenRouteWithChildren = SimuladoTokenRoute._addFileChildren(
  SimuladoTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SimuladoTokenRoute: SimuladoTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
